import {
  StyleSheet,
} from 'react-native';

const SimStyle = StyleSheet.create({
  topLogo: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    width: 428,
    height: 100,
    left: 0,
    top: 0
  },
  selectSimToLogin: {
    color: "rgba(155, 147, 147, 1)",
    fontSize: 22,
    fontWeight: "700",
    fontStyle: "normal",
    fontFamily: "Arial",
    textAlign: "left",
    "width": 209,
    "height": 30,
    "marginTop": 40,
    "marginLeft": 90,
  },
  "rectangle1": {
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 35,
    "borderTopRightRadius": 35,
    "borderBottomLeftRadius": 35,
    "borderBottomRightRadius": 35,
    "width": 159,
    "height": 245,
  },
  "sim1_img": {
    "marginTop": 50,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 20,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 112,
    "height": 112,
  },
  "sim1": {
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(155, 147, 147, 1)",
    "fontSize": 20,
    "fontWeight": "100",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "center",
    "marginTop": 10,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 50,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 59,
    "height": 25
  },
  "rectangle2": {
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "borderTopWidth": 1,
    "borderTopColor": "rgba(112, 112, 112, 1)",
    "borderRightWidth": 1,
    "borderRightColor": "rgba(112, 112, 112, 1)",
    "borderBottomWidth": 1,
    "borderBottomColor": "rgba(112, 112, 112, 1)",
    "borderLeftWidth": 1,
    "borderLeftColor": "rgba(112, 112, 112, 1)",
    "borderTopLeftRadius": 35,
    "borderTopRightRadius": 35,
    "borderBottomLeftRadius": 35,
    "borderBottomRightRadius": 35,
    "width": 159,
    "height": 245,
  },
  "sim2_img": {
    "opacity": 1,
    "position": "absolute",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "borderTopLeftRadius": 0,
    "borderTopRightRadius": 0,
    "borderBottomLeftRadius": 0,
    "borderBottomRightRadius": 0,
    "width": 111,
    "height": 111,
    "left": 252.5,
    "top": 360.5
  },
  "sim2": {
    "opacity": 1,
    "position": "absolute",
    "backgroundColor": "rgba(255, 255, 255, 0)",
    "color": "rgba(155, 147, 147, 1)",
    "fontSize": 22,
    "fontWeight": "700",
    "fontStyle": "normal",
    "fontFamily": "Arial",
    "textAlign": "left",
    "marginTop": 0,
    "marginRight": 0,
    "marginBottom": 0,
    "marginLeft": 0,
    "paddingTop": 0,
    "paddingRight": 0,
    "paddingBottom": 0,
    "paddingLeft": 0,
    "width": 59,
    "height": 25,
    "left": 279,
    "top": 492
  }
});

export default SimStyle